Add verbose requirements diff
Signed-off-by: Takahiro Nagasawa <takahiro.nagasawa@proton.me>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,7 +28,9 @@ jobs:
       - name: Check if requirements.txt is up to date
         run: |
           pip-compile api/requirements.in -o api/requirements.txt --upgrade --no-strip-extras
-          git diff --exit-code --quiet api/requirements.txt || (echo "requirements.txt is not up to date. Please run 'pip-compile api/requirements.in -o api/requirements.txt --upgrade' and commit the changes." && exit 1)
+          echo "git diff of requirements.txt:"
+          git diff --no-color api/requirements.txt
+          git diff --exit-code --quiet api/requirements.txt || (echo "ERROR: requirements.txt is not up to date. Please run 'pip-compile api/requirements.in -o api/requirements.txt --upgrade --no-strip-extras' and commit the changes." && exit 1)
 
       - name: Install dependencies
         run: pip-sync api/requirements.txt
